# Generated by Django 5.0.6 on 2024-07-07 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0004_alter_curso_nivel_alter_curso_paralelo'),
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nulo', models.BooleanField(blank=True, default=False)),
                ('blanco', models.BooleanField(blank=True, default=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
                ('lista', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lista.lista')),
            ],
        ),
    ]
