# Generated by Django 5.0.6 on 2024-07-07 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0004_alter_curso_nivel_alter_curso_paralelo'),
        ('voto', '0002_alter_voto_blanco_alter_voto_estudiante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante', unique=True),
        ),
    ]
