# Generated by Django 5.0.6 on 2024-07-07 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0004_alter_curso_nivel_alter_curso_paralelo'),
        ('voto', '0005_alter_voto_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='estudiante',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante'),
        ),
    ]
