# Generated by Django 5.0.6 on 2024-07-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voto', '0007_alter_voto_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='blanco',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='nulo',
        ),
    ]
