# Generated by Django 5.0.6 on 2024-07-06 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dignidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dignidad', models.CharField(choices=[('Presidente', 'presidente'), ('Vicepresidente', 'vicepresidente'), ('Secretario/a', 'vecretario/a'), ('Tesorero/a', 'tesorero/a'), ('Vocal-1', 'vocal-1'), ('Vocal-2', 'vocal-2')], default='Presi', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lista.lista')),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante')),
                ('dignidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidato.dignidad')),
            ],
        ),
    ]
