# Generated by Django 5.0.6 on 2024-07-06 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dignidad',
            name='dignidad',
            field=models.CharField(choices=[('presidente', 'Presidente'), ('vicepresidente', 'Vicepresidente'), ('secretario/a', 'Secretario/a'), ('tesorero/a', 'Tesorero/a'), ('vocal-1', 'Vocal-1'), ('vocal-2', 'Vocal-2')], default='Presi', max_length=30),
        ),
    ]
