# Generated by Django 5.0.6 on 2024-07-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_alter_dignidad_dignidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dignidad',
            name='dignidad',
            field=models.CharField(choices=[('Presidente', 'presidente'), ('Vicepresidente', 'vicepresidente'), ('Secretario/a', 'secretario/a'), ('Tesorero/a', 'tesorero/a'), ('Vocal-1', 'vocal-1'), ('Vocal-2', 'vocal-2')], default='Presi', max_length=30),
        ),
    ]
