# Generated by Django 5.0.6 on 2024-07-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0003_alter_dignidad_dignidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='nombre',
            new_name='estudiante',
        ),
        migrations.AddField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(default='', upload_to='candidatos'),
            preserve_default=False,
        ),
    ]
