# Generated by Django 5.0.6 on 2024-07-16 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0004_rename_nombre_candidato_estudiante_candidato_foto'),
        ('lista', '0003_alter_lista_nombre_alter_lista_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='lista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='lista.lista'),
        ),
    ]
