# Generated by Django 5.0.6 on 2024-07-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0005_alter_candidato_lista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='foto',
            field=models.ImageField(upload_to='listas'),
        ),
    ]
